//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketService.TicketServiceSoap")]
    public interface TicketServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.CreateUsersResponse> CreateUsersAsync(TicketService.CreateUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.CreateBugsResponse> CreateBugsAsync(TicketService.CreateBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.CreateTicketsResponse> CreateTicketsAsync(TicketService.CreateTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.UpdateUsersResponse> UpdateUsersAsync(TicketService.UpdateUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.UpdateBugsResponse> UpdateBugsAsync(TicketService.UpdateBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.UpdateTicketsResponse> UpdateTicketsAsync(TicketService.UpdateTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.GetUsersResponse> GetUsersAsync(TicketService.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.GetBugsResponse> GetBugsAsync(TicketService.GetBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketService.GetTicketsResponse> GetTicketsAsync(TicketService.GetTicketsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateUsersRequestBody Body;
        
        public CreateUsersRequest()
        {
        }
        
        public CreateUsersRequest(TicketService.CreateUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUsersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UserTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateUsersRequestBody()
        {
        }
        
        public CreateUsersRequestBody(string AuthenticationCode, string Name, string Password, int UserTypeID, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Name = Name;
            this.Password = Password;
            this.UserTypeID = UserTypeID;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateUsersResponseBody Body;
        
        public CreateUsersResponse()
        {
        }
        
        public CreateUsersResponse(TicketService.CreateUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateUsersResponseBody
    {
        
        public CreateUsersResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBugsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateBugsRequestBody Body;
        
        public CreateBugsRequest()
        {
        }
        
        public CreateBugsRequest(TicketService.CreateBugsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBugsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateBugsRequestBody()
        {
        }
        
        public CreateBugsRequestBody(string AuthenticationCode, string Name, string Des, string Summary, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Name = Name;
            this.Des = Des;
            this.Summary = Summary;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBugsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateBugsResponseBody Body;
        
        public CreateBugsResponse()
        {
        }
        
        public CreateBugsResponse(TicketService.CreateBugsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateBugsResponseBody
    {
        
        public CreateBugsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTicketsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateTicketsRequestBody Body;
        
        public CreateTicketsRequest()
        {
        }
        
        public CreateTicketsRequest(TicketService.CreateTicketsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTicketsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsResolved;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateTicketsRequestBody()
        {
        }
        
        public CreateTicketsRequestBody(string AuthenticationCode, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.TicketTypeId = TicketTypeId;
            this.Des = Des;
            this.IsResolved = IsResolved;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTicketsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.CreateTicketsResponseBody Body;
        
        public CreateTicketsResponse()
        {
        }
        
        public CreateTicketsResponse(TicketService.CreateTicketsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateTicketsResponseBody
    {
        
        public CreateTicketsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateUsersRequestBody Body;
        
        public UpdateUsersRequest()
        {
        }
        
        public UpdateUsersRequest(TicketService.UpdateUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUsersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UserTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateUsersRequestBody()
        {
        }
        
        public UpdateUsersRequestBody(string AuthenticationCode, int Id, string Name, string Password, int UserTypeID, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Password = Password;
            this.UserTypeID = UserTypeID;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateUsersResponseBody Body;
        
        public UpdateUsersResponse()
        {
        }
        
        public UpdateUsersResponse(TicketService.UpdateUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUsersResponseBody
    {
        
        public UpdateUsersResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBugsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateBugsRequestBody Body;
        
        public UpdateBugsRequest()
        {
        }
        
        public UpdateBugsRequest(TicketService.UpdateBugsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBugsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateBugsRequestBody()
        {
        }
        
        public UpdateBugsRequestBody(string AuthenticationCode, int Id, string Name, string Des, string Summary, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Des = Des;
            this.Summary = Summary;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBugsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateBugsResponseBody Body;
        
        public UpdateBugsResponse()
        {
        }
        
        public UpdateBugsResponse(TicketService.UpdateBugsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateBugsResponseBody
    {
        
        public UpdateBugsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTicketsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateTicketsRequestBody Body;
        
        public UpdateTicketsRequest()
        {
        }
        
        public UpdateTicketsRequest(TicketService.UpdateTicketsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTicketsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> IsResolved;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateTicketsRequestBody()
        {
        }
        
        public UpdateTicketsRequestBody(string AuthenticationCode, int Id, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.TicketTypeId = TicketTypeId;
            this.Des = Des;
            this.IsResolved = IsResolved;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTicketsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.UpdateTicketsResponseBody Body;
        
        public UpdateTicketsResponse()
        {
        }
        
        public UpdateTicketsResponse(TicketService.UpdateTicketsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTicketsResponseBody
    {
        
        public UpdateTicketsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetUsersRequestBody Body;
        
        public GetUsersRequest()
        {
        }
        
        public GetUsersRequest(TicketService.GetUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public GetUsersRequestBody()
        {
        }
        
        public GetUsersRequestBody(string AuthenticationCode, int Id, string Name, string Password)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetUsersResponseBody Body;
        
        public GetUsersResponse()
        {
        }
        
        public GetUsersResponse(TicketService.GetUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersResponseBody
    {
        
        public GetUsersResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBugsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetBugsRequestBody Body;
        
        public GetBugsRequest()
        {
        }
        
        public GetBugsRequest(TicketService.GetBugsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBugsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> Resolved;
        
        public GetBugsRequestBody()
        {
        }
        
        public GetBugsRequestBody(string AuthenticationCode, int Id, string Name, System.Nullable<bool> Resolved)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Resolved = Resolved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBugsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetBugsResponseBody Body;
        
        public GetBugsResponse()
        {
        }
        
        public GetBugsResponse(TicketService.GetBugsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBugsResponseBody
    {
        
        public GetBugsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetTicketsRequestBody Body;
        
        public GetTicketsRequest()
        {
        }
        
        public GetTicketsRequest(TicketService.GetTicketsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsResolved;
        
        public GetTicketsRequestBody()
        {
        }
        
        public GetTicketsRequestBody(string AuthenticationCode, int Id, int TicketTypeId, System.Nullable<bool> IsResolved)
        {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.TicketTypeId = TicketTypeId;
            this.IsResolved = IsResolved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketService.GetTicketsResponseBody Body;
        
        public GetTicketsResponse()
        {
        }
        
        public GetTicketsResponse(TicketService.GetTicketsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTicketsResponseBody
    {
        
        public GetTicketsResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TicketServiceSoapChannel : TicketService.TicketServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TicketServiceSoapClient : System.ServiceModel.ClientBase<TicketService.TicketServiceSoap>, TicketService.TicketServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TicketServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TicketServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TicketServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TicketServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TicketServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.CreateUsersResponse> TicketService.TicketServiceSoap.CreateUsersAsync(TicketService.CreateUsersRequest request)
        {
            return base.Channel.CreateUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.CreateUsersResponse> CreateUsersAsync(string AuthenticationCode, string Name, string Password, int UserTypeID, int UpdatedBy)
        {
            TicketService.CreateUsersRequest inValue = new TicketService.CreateUsersRequest();
            inValue.Body = new TicketService.CreateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).CreateUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.CreateBugsResponse> TicketService.TicketServiceSoap.CreateBugsAsync(TicketService.CreateBugsRequest request)
        {
            return base.Channel.CreateBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.CreateBugsResponse> CreateBugsAsync(string AuthenticationCode, string Name, string Des, string Summary, int UpdatedBy)
        {
            TicketService.CreateBugsRequest inValue = new TicketService.CreateBugsRequest();
            inValue.Body = new TicketService.CreateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).CreateBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.CreateTicketsResponse> TicketService.TicketServiceSoap.CreateTicketsAsync(TicketService.CreateTicketsRequest request)
        {
            return base.Channel.CreateTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.CreateTicketsResponse> CreateTicketsAsync(string AuthenticationCode, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy)
        {
            TicketService.CreateTicketsRequest inValue = new TicketService.CreateTicketsRequest();
            inValue.Body = new TicketService.CreateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).CreateTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.UpdateUsersResponse> TicketService.TicketServiceSoap.UpdateUsersAsync(TicketService.UpdateUsersRequest request)
        {
            return base.Channel.UpdateUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.UpdateUsersResponse> UpdateUsersAsync(string AuthenticationCode, int Id, string Name, string Password, int UserTypeID, int UpdatedBy)
        {
            TicketService.UpdateUsersRequest inValue = new TicketService.UpdateUsersRequest();
            inValue.Body = new TicketService.UpdateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).UpdateUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.UpdateBugsResponse> TicketService.TicketServiceSoap.UpdateBugsAsync(TicketService.UpdateBugsRequest request)
        {
            return base.Channel.UpdateBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.UpdateBugsResponse> UpdateBugsAsync(string AuthenticationCode, int Id, string Name, string Des, string Summary, int UpdatedBy)
        {
            TicketService.UpdateBugsRequest inValue = new TicketService.UpdateBugsRequest();
            inValue.Body = new TicketService.UpdateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).UpdateBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.UpdateTicketsResponse> TicketService.TicketServiceSoap.UpdateTicketsAsync(TicketService.UpdateTicketsRequest request)
        {
            return base.Channel.UpdateTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.UpdateTicketsResponse> UpdateTicketsAsync(string AuthenticationCode, int Id, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy)
        {
            TicketService.UpdateTicketsRequest inValue = new TicketService.UpdateTicketsRequest();
            inValue.Body = new TicketService.UpdateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketService.TicketServiceSoap)(this)).UpdateTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.GetUsersResponse> TicketService.TicketServiceSoap.GetUsersAsync(TicketService.GetUsersRequest request)
        {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.GetUsersResponse> GetUsersAsync(string AuthenticationCode, int Id, string Name, string Password)
        {
            TicketService.GetUsersRequest inValue = new TicketService.GetUsersRequest();
            inValue.Body = new TicketService.GetUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            return ((TicketService.TicketServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.GetBugsResponse> TicketService.TicketServiceSoap.GetBugsAsync(TicketService.GetBugsRequest request)
        {
            return base.Channel.GetBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.GetBugsResponse> GetBugsAsync(string AuthenticationCode, int Id, string Name, System.Nullable<bool> Resolved)
        {
            TicketService.GetBugsRequest inValue = new TicketService.GetBugsRequest();
            inValue.Body = new TicketService.GetBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Resolved = Resolved;
            return ((TicketService.TicketServiceSoap)(this)).GetBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketService.GetTicketsResponse> TicketService.TicketServiceSoap.GetTicketsAsync(TicketService.GetTicketsRequest request)
        {
            return base.Channel.GetTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketService.GetTicketsResponse> GetTicketsAsync(string AuthenticationCode, int Id, int TicketTypeId, System.Nullable<bool> IsResolved)
        {
            TicketService.GetTicketsRequest inValue = new TicketService.GetTicketsRequest();
            inValue.Body = new TicketService.GetTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.IsResolved = IsResolved;
            return ((TicketService.TicketServiceSoap)(this)).GetTicketsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TicketServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TicketServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TicketServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TicketServices/WebAPI/TicketService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TicketServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TicketServices/WebAPI/TicketService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TicketServiceSoap,
            
            TicketServiceSoap12,
        }
    }
}
