//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketServices.TicketService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketService.TicketServiceSoap")]
    public interface TicketServiceSoap {
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUsers", ReplyAction="*")]
        TicketServices.TicketService.CreateUsersResponse CreateUsers(TicketServices.TicketService.CreateUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateUsersResponse> CreateUsersAsync(TicketServices.TicketService.CreateUsersRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBugs", ReplyAction="*")]
        TicketServices.TicketService.CreateBugsResponse CreateBugs(TicketServices.TicketService.CreateBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateBugsResponse> CreateBugsAsync(TicketServices.TicketService.CreateBugsRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTickets", ReplyAction="*")]
        TicketServices.TicketService.CreateTicketsResponse CreateTickets(TicketServices.TicketService.CreateTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateTicketsResponse> CreateTicketsAsync(TicketServices.TicketService.CreateTicketsRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsers", ReplyAction="*")]
        TicketServices.TicketService.UpdateUsersResponse UpdateUsers(TicketServices.TicketService.UpdateUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateUsersResponse> UpdateUsersAsync(TicketServices.TicketService.UpdateUsersRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBugs", ReplyAction="*")]
        TicketServices.TicketService.UpdateBugsResponse UpdateBugs(TicketServices.TicketService.UpdateBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateBugsResponse> UpdateBugsAsync(TicketServices.TicketService.UpdateBugsRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTickets", ReplyAction="*")]
        TicketServices.TicketService.UpdateTicketsResponse UpdateTickets(TicketServices.TicketService.UpdateTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateTicketsResponse> UpdateTicketsAsync(TicketServices.TicketService.UpdateTicketsRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        TicketServices.TicketService.GetUsersResponse GetUsers(TicketServices.TicketService.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetUsersResponse> GetUsersAsync(TicketServices.TicketService.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBugs", ReplyAction="*")]
        TicketServices.TicketService.GetBugsResponse GetBugs(TicketServices.TicketService.GetBugsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBugs", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetBugsResponse> GetBugsAsync(TicketServices.TicketService.GetBugsRequest request);
        
        // CODEGEN: Generating message contract since element name AuthenticationCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTickets", ReplyAction="*")]
        TicketServices.TicketService.GetTicketsResponse GetTickets(TicketServices.TicketService.GetTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetTicketsResponse> GetTicketsAsync(TicketServices.TicketService.GetTicketsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateUsersRequestBody Body;
        
        public CreateUsersRequest() {
        }
        
        public CreateUsersRequest(TicketServices.TicketService.CreateUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UserTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateUsersRequestBody() {
        }
        
        public CreateUsersRequestBody(string AuthenticationCode, string Name, string Password, int UserTypeID, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.Name = Name;
            this.Password = Password;
            this.UserTypeID = UserTypeID;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateUsersResponseBody Body;
        
        public CreateUsersResponse() {
        }
        
        public CreateUsersResponse(TicketServices.TicketService.CreateUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateUsersResponseBody {
        
        public CreateUsersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBugsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateBugsRequestBody Body;
        
        public CreateBugsRequest() {
        }
        
        public CreateBugsRequest(TicketServices.TicketService.CreateBugsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateBugsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateBugsRequestBody() {
        }
        
        public CreateBugsRequestBody(string AuthenticationCode, string Name, string Des, string Summary, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.Name = Name;
            this.Des = Des;
            this.Summary = Summary;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateBugsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateBugsResponseBody Body;
        
        public CreateBugsResponse() {
        }
        
        public CreateBugsResponse(TicketServices.TicketService.CreateBugsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateBugsResponseBody {
        
        public CreateBugsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateTicketsRequestBody Body;
        
        public CreateTicketsRequest() {
        }
        
        public CreateTicketsRequest(TicketServices.TicketService.CreateTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsResolved;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdatedBy;
        
        public CreateTicketsRequestBody() {
        }
        
        public CreateTicketsRequestBody(string AuthenticationCode, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.TicketTypeId = TicketTypeId;
            this.Des = Des;
            this.IsResolved = IsResolved;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.CreateTicketsResponseBody Body;
        
        public CreateTicketsResponse() {
        }
        
        public CreateTicketsResponse(TicketServices.TicketService.CreateTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateTicketsResponseBody {
        
        public CreateTicketsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateUsersRequestBody Body;
        
        public UpdateUsersRequest() {
        }
        
        public UpdateUsersRequest(TicketServices.TicketService.UpdateUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UserTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateUsersRequestBody() {
        }
        
        public UpdateUsersRequestBody(string AuthenticationCode, int Id, string Name, string Password, int UserTypeID, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Password = Password;
            this.UserTypeID = UserTypeID;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateUsersResponseBody Body;
        
        public UpdateUsersResponse() {
        }
        
        public UpdateUsersResponse(TicketServices.TicketService.UpdateUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUsersResponseBody {
        
        public UpdateUsersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBugsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateBugsRequestBody Body;
        
        public UpdateBugsRequest() {
        }
        
        public UpdateBugsRequest(TicketServices.TicketService.UpdateBugsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBugsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Summary;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateBugsRequestBody() {
        }
        
        public UpdateBugsRequestBody(string AuthenticationCode, int Id, string Name, string Des, string Summary, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Des = Des;
            this.Summary = Summary;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBugsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateBugsResponseBody Body;
        
        public UpdateBugsResponse() {
        }
        
        public UpdateBugsResponse(TicketServices.TicketService.UpdateBugsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateBugsResponseBody {
        
        public UpdateBugsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateTicketsRequestBody Body;
        
        public UpdateTicketsRequest() {
        }
        
        public UpdateTicketsRequest(TicketServices.TicketService.UpdateTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Des;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> IsResolved;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UpdatedBy;
        
        public UpdateTicketsRequestBody() {
        }
        
        public UpdateTicketsRequestBody(string AuthenticationCode, int Id, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.TicketTypeId = TicketTypeId;
            this.Des = Des;
            this.IsResolved = IsResolved;
            this.UpdatedBy = UpdatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.UpdateTicketsResponseBody Body;
        
        public UpdateTicketsResponse() {
        }
        
        public UpdateTicketsResponse(TicketServices.TicketService.UpdateTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTicketsResponseBody {
        
        public UpdateTicketsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(TicketServices.TicketService.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public GetUsersRequestBody() {
        }
        
        public GetUsersRequestBody(string AuthenticationCode, int Id, string Name, string Password) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(TicketServices.TicketService.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersResponseBody {
        
        public GetUsersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBugsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBugs", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetBugsRequestBody Body;
        
        public GetBugsRequest() {
        }
        
        public GetBugsRequest(TicketServices.TicketService.GetBugsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBugsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> Resolved;
        
        public GetBugsRequestBody() {
        }
        
        public GetBugsRequestBody(string AuthenticationCode, int Id, string Name, System.Nullable<bool> Resolved) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.Name = Name;
            this.Resolved = Resolved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBugsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBugsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetBugsResponseBody Body;
        
        public GetBugsResponse() {
        }
        
        public GetBugsResponse(TicketServices.TicketService.GetBugsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBugsResponseBody {
        
        public GetBugsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTickets", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetTicketsRequestBody Body;
        
        public GetTicketsRequest() {
        }
        
        public GetTicketsRequest(TicketServices.TicketService.GetTicketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTicketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TicketTypeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsResolved;
        
        public GetTicketsRequestBody() {
        }
        
        public GetTicketsRequestBody(string AuthenticationCode, int Id, int TicketTypeId, System.Nullable<bool> IsResolved) {
            this.AuthenticationCode = AuthenticationCode;
            this.Id = Id;
            this.TicketTypeId = TicketTypeId;
            this.IsResolved = IsResolved;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTicketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TicketServices.TicketService.GetTicketsResponseBody Body;
        
        public GetTicketsResponse() {
        }
        
        public GetTicketsResponse(TicketServices.TicketService.GetTicketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTicketsResponseBody {
        
        public GetTicketsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TicketServiceSoapChannel : TicketServices.TicketService.TicketServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketServiceSoapClient : System.ServiceModel.ClientBase<TicketServices.TicketService.TicketServiceSoap>, TicketServices.TicketService.TicketServiceSoap {
        
        public TicketServiceSoapClient() {
        }
        
        public TicketServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.CreateUsersResponse TicketServices.TicketService.TicketServiceSoap.CreateUsers(TicketServices.TicketService.CreateUsersRequest request) {
            return base.Channel.CreateUsers(request);
        }
        
        public void CreateUsers(string AuthenticationCode, string Name, string Password, int UserTypeID, int UpdatedBy) {
            TicketServices.TicketService.CreateUsersRequest inValue = new TicketServices.TicketService.CreateUsersRequest();
            inValue.Body = new TicketServices.TicketService.CreateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.CreateUsersResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateUsersResponse> TicketServices.TicketService.TicketServiceSoap.CreateUsersAsync(TicketServices.TicketService.CreateUsersRequest request) {
            return base.Channel.CreateUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.CreateUsersResponse> CreateUsersAsync(string AuthenticationCode, string Name, string Password, int UserTypeID, int UpdatedBy) {
            TicketServices.TicketService.CreateUsersRequest inValue = new TicketServices.TicketService.CreateUsersRequest();
            inValue.Body = new TicketServices.TicketService.CreateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.CreateBugsResponse TicketServices.TicketService.TicketServiceSoap.CreateBugs(TicketServices.TicketService.CreateBugsRequest request) {
            return base.Channel.CreateBugs(request);
        }
        
        public void CreateBugs(string AuthenticationCode, string Name, string Des, string Summary, int UpdatedBy) {
            TicketServices.TicketService.CreateBugsRequest inValue = new TicketServices.TicketService.CreateBugsRequest();
            inValue.Body = new TicketServices.TicketService.CreateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.CreateBugsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateBugs(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateBugsResponse> TicketServices.TicketService.TicketServiceSoap.CreateBugsAsync(TicketServices.TicketService.CreateBugsRequest request) {
            return base.Channel.CreateBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.CreateBugsResponse> CreateBugsAsync(string AuthenticationCode, string Name, string Des, string Summary, int UpdatedBy) {
            TicketServices.TicketService.CreateBugsRequest inValue = new TicketServices.TicketService.CreateBugsRequest();
            inValue.Body = new TicketServices.TicketService.CreateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.CreateTicketsResponse TicketServices.TicketService.TicketServiceSoap.CreateTickets(TicketServices.TicketService.CreateTicketsRequest request) {
            return base.Channel.CreateTickets(request);
        }
        
        public void CreateTickets(string AuthenticationCode, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            TicketServices.TicketService.CreateTicketsRequest inValue = new TicketServices.TicketService.CreateTicketsRequest();
            inValue.Body = new TicketServices.TicketService.CreateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.CreateTicketsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateTickets(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.CreateTicketsResponse> TicketServices.TicketService.TicketServiceSoap.CreateTicketsAsync(TicketServices.TicketService.CreateTicketsRequest request) {
            return base.Channel.CreateTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.CreateTicketsResponse> CreateTicketsAsync(string AuthenticationCode, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            TicketServices.TicketService.CreateTicketsRequest inValue = new TicketServices.TicketService.CreateTicketsRequest();
            inValue.Body = new TicketServices.TicketService.CreateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).CreateTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.UpdateUsersResponse TicketServices.TicketService.TicketServiceSoap.UpdateUsers(TicketServices.TicketService.UpdateUsersRequest request) {
            return base.Channel.UpdateUsers(request);
        }
        
        public void UpdateUsers(string AuthenticationCode, int Id, string Name, string Password, int UserTypeID, int UpdatedBy) {
            TicketServices.TicketService.UpdateUsersRequest inValue = new TicketServices.TicketService.UpdateUsersRequest();
            inValue.Body = new TicketServices.TicketService.UpdateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.UpdateUsersResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateUsersResponse> TicketServices.TicketService.TicketServiceSoap.UpdateUsersAsync(TicketServices.TicketService.UpdateUsersRequest request) {
            return base.Channel.UpdateUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.UpdateUsersResponse> UpdateUsersAsync(string AuthenticationCode, int Id, string Name, string Password, int UserTypeID, int UpdatedBy) {
            TicketServices.TicketService.UpdateUsersRequest inValue = new TicketServices.TicketService.UpdateUsersRequest();
            inValue.Body = new TicketServices.TicketService.UpdateUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            inValue.Body.UserTypeID = UserTypeID;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.UpdateBugsResponse TicketServices.TicketService.TicketServiceSoap.UpdateBugs(TicketServices.TicketService.UpdateBugsRequest request) {
            return base.Channel.UpdateBugs(request);
        }
        
        public void UpdateBugs(string AuthenticationCode, int Id, string Name, string Des, string Summary, int UpdatedBy) {
            TicketServices.TicketService.UpdateBugsRequest inValue = new TicketServices.TicketService.UpdateBugsRequest();
            inValue.Body = new TicketServices.TicketService.UpdateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.UpdateBugsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateBugs(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateBugsResponse> TicketServices.TicketService.TicketServiceSoap.UpdateBugsAsync(TicketServices.TicketService.UpdateBugsRequest request) {
            return base.Channel.UpdateBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.UpdateBugsResponse> UpdateBugsAsync(string AuthenticationCode, int Id, string Name, string Des, string Summary, int UpdatedBy) {
            TicketServices.TicketService.UpdateBugsRequest inValue = new TicketServices.TicketService.UpdateBugsRequest();
            inValue.Body = new TicketServices.TicketService.UpdateBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Des = Des;
            inValue.Body.Summary = Summary;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.UpdateTicketsResponse TicketServices.TicketService.TicketServiceSoap.UpdateTickets(TicketServices.TicketService.UpdateTicketsRequest request) {
            return base.Channel.UpdateTickets(request);
        }
        
        public void UpdateTickets(string AuthenticationCode, int Id, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            TicketServices.TicketService.UpdateTicketsRequest inValue = new TicketServices.TicketService.UpdateTicketsRequest();
            inValue.Body = new TicketServices.TicketService.UpdateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            TicketServices.TicketService.UpdateTicketsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateTickets(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.UpdateTicketsResponse> TicketServices.TicketService.TicketServiceSoap.UpdateTicketsAsync(TicketServices.TicketService.UpdateTicketsRequest request) {
            return base.Channel.UpdateTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.UpdateTicketsResponse> UpdateTicketsAsync(string AuthenticationCode, int Id, int TicketTypeId, string Des, System.Nullable<bool> IsResolved, int UpdatedBy) {
            TicketServices.TicketService.UpdateTicketsRequest inValue = new TicketServices.TicketService.UpdateTicketsRequest();
            inValue.Body = new TicketServices.TicketService.UpdateTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.Des = Des;
            inValue.Body.IsResolved = IsResolved;
            inValue.Body.UpdatedBy = UpdatedBy;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).UpdateTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.GetUsersResponse TicketServices.TicketService.TicketServiceSoap.GetUsers(TicketServices.TicketService.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public void GetUsers(string AuthenticationCode, int Id, string Name, string Password) {
            TicketServices.TicketService.GetUsersRequest inValue = new TicketServices.TicketService.GetUsersRequest();
            inValue.Body = new TicketServices.TicketService.GetUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            TicketServices.TicketService.GetUsersResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).GetUsers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetUsersResponse> TicketServices.TicketService.TicketServiceSoap.GetUsersAsync(TicketServices.TicketService.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.GetUsersResponse> GetUsersAsync(string AuthenticationCode, int Id, string Name, string Password) {
            TicketServices.TicketService.GetUsersRequest inValue = new TicketServices.TicketService.GetUsersRequest();
            inValue.Body = new TicketServices.TicketService.GetUsersRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Password = Password;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.GetBugsResponse TicketServices.TicketService.TicketServiceSoap.GetBugs(TicketServices.TicketService.GetBugsRequest request) {
            return base.Channel.GetBugs(request);
        }
        
        public void GetBugs(string AuthenticationCode, int Id, string Name, System.Nullable<bool> Resolved) {
            TicketServices.TicketService.GetBugsRequest inValue = new TicketServices.TicketService.GetBugsRequest();
            inValue.Body = new TicketServices.TicketService.GetBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Resolved = Resolved;
            TicketServices.TicketService.GetBugsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).GetBugs(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetBugsResponse> TicketServices.TicketService.TicketServiceSoap.GetBugsAsync(TicketServices.TicketService.GetBugsRequest request) {
            return base.Channel.GetBugsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.GetBugsResponse> GetBugsAsync(string AuthenticationCode, int Id, string Name, System.Nullable<bool> Resolved) {
            TicketServices.TicketService.GetBugsRequest inValue = new TicketServices.TicketService.GetBugsRequest();
            inValue.Body = new TicketServices.TicketService.GetBugsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.Name = Name;
            inValue.Body.Resolved = Resolved;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).GetBugsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TicketServices.TicketService.GetTicketsResponse TicketServices.TicketService.TicketServiceSoap.GetTickets(TicketServices.TicketService.GetTicketsRequest request) {
            return base.Channel.GetTickets(request);
        }
        
        public void GetTickets(string AuthenticationCode, int Id, int TicketTypeId, System.Nullable<bool> IsResolved) {
            TicketServices.TicketService.GetTicketsRequest inValue = new TicketServices.TicketService.GetTicketsRequest();
            inValue.Body = new TicketServices.TicketService.GetTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.IsResolved = IsResolved;
            TicketServices.TicketService.GetTicketsResponse retVal = ((TicketServices.TicketService.TicketServiceSoap)(this)).GetTickets(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TicketServices.TicketService.GetTicketsResponse> TicketServices.TicketService.TicketServiceSoap.GetTicketsAsync(TicketServices.TicketService.GetTicketsRequest request) {
            return base.Channel.GetTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TicketServices.TicketService.GetTicketsResponse> GetTicketsAsync(string AuthenticationCode, int Id, int TicketTypeId, System.Nullable<bool> IsResolved) {
            TicketServices.TicketService.GetTicketsRequest inValue = new TicketServices.TicketService.GetTicketsRequest();
            inValue.Body = new TicketServices.TicketService.GetTicketsRequestBody();
            inValue.Body.AuthenticationCode = AuthenticationCode;
            inValue.Body.Id = Id;
            inValue.Body.TicketTypeId = TicketTypeId;
            inValue.Body.IsResolved = IsResolved;
            return ((TicketServices.TicketService.TicketServiceSoap)(this)).GetTicketsAsync(inValue);
        }
    }
}
